### ISSUE TITLE
Allow developers to create custom links

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/MagiCircles#45]
![image](https://user-images.githubusercontent.com/30684769/42357416-a36ee8e0-808c-11e8-9083-6e6126a0fed1.png))
Allow developers to create custom tab fields like "Favorite Band", and (maybe) allow them to modify/delete some pre-existing template ones (like top 3 fav characters, since people have complained about that). Making these adjustable will allow the sites to naturally gain their own identity more easily, and will help users to more easily share info about themselves on each site without making a LONG profile bio.

**Comment by db0company** [comment]
Closed by https://github.com/MagiCircles/MagiCircles/commit/e5a04dd738e74095c78b90c19a99dc73da0f58cf
