### ISSUE TITLE
Hide filter for liked activities when logged out

### ISSUE THREAD

**Issue by db0company** [MagiCircles/MagiCircles#61]

**Comment by LatidoReMe** [comment]
I don't have the ability to actually create a branch for this repo, but I think all you need to do for this is change the code here: https://github.com/MagiCircles/MagiCircles/blob/17d0877efcb6478c9d61337bc9b70127735fc35c/magi/forms.py#L1591-L1592
to the code down below
```
if not self.request.user.is_authenticated():
            if 'is_following' in self.fields:
                del(self.fields['is_following'])
            if 'liked' in self.fields:
                del(self.fields['liked'])
```

**Comment by NanduTej** [comment]
Hi, I am beginner. Is this issue still open? And if so, please you help me out with how to start contributing.

**Comment by arshadkazmi42** [comment]
> if not self.request.user.is_authenticated(): if 'is_following' in self.fields: del(self.fields['is_following']) if 'liked' in self.fields: del(self.fields['liked'])

made this change. creating a PR now.
