### ISSUE TITLE
Add Bandori.Party Icon to static/img/links

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/MagiCircles#69]
Currently, Bandori.Party is available in the list of links, as shown here:
https://github.com/MagiCircles/MagiCircles/blob/18b2203a468562403a54e2f403d2217c4fe5c88c/magi/models.py#L407-L413

However, there is no "bang" image in https://github.com/MagiCircles/MagiCircles/tree/master/magi/static/img/links

Currently this isn't urgent as no site actually uses the link for BanPa, but it'll have to be done before the launch of SITv2 unless we want 1 random broken image like this:
![image](https://user-images.githubusercontent.com/30684769/46275221-10192780-c511-11e8-89d2-6c2cd1d82961.png)

**Comment by arshadkazmi42** [comment]
taking this up

**Comment by arshadkazmi42** [comment]
looks like this has already been fixed. i can see the icon available here

https://github.com/MagiCircles/MagiCircles/blob/master/magi/static/img/links/bang.png
