### ISSUE TITLE
Re-enable % chance in RANDOM_ART_FOR_CHARACTER

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/MagiCircles#89]
While the MagiCircles wiki states that RANDOM_ART_FOR_CHARACTER will only run 20% of the time, the end of this snippet makes it run 100%
https://github.com/MagiCircles/MagiCircles/blob/9f11ed6fc0546ec1fdcb093225bb3d471ae7860c/magi/views.py#L208-L211
Since some sites like BanPa might not want that, I suggest either converting it back to the 20% (replace the True with the randint) or creating an extra "setting" to RANDOM_ART_FOR_CHARACTER where we can choose the percentage per-site.

**Comment by db0company** [comment]
Closed by https://github.com/MagiCircles/MagiCircles/commit/649fe1290f8f434cd4e8b1fef83d38c5bc039f89
